/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 36
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 25
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 9
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACE = 1,
  anon_sym_RBRACE = 2,
  sym_identifier = 3,
  sym_identifier_disabled = 4,
  sym_comment = 5,
  aux_sym_key_value_token1 = 6,
  anon_sym_Declare = 7,
  anon_sym_EQ = 8,
  anon_sym_Include = 9,
  sym_include_path = 10,
  sym_string = 11,
  sym_env_path = 12,
  sym_bare_value = 13,
  sym_source_file = 14,
  sym__statement = 15,
  sym_leafblock = 16,
  sym_leafblock_disabled = 17,
  sym_key_value = 18,
  sym_key_value_disabled = 19,
  sym__value = 20,
  sym_declare = 21,
  sym_include = 22,
  aux_sym_source_file_repeat1 = 23,
  aux_sym_key_value_repeat1 = 24,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_identifier] = "identifier",
  [sym_identifier_disabled] = "identifier_disabled",
  [sym_comment] = "comment",
  [aux_sym_key_value_token1] = "key_value_token1",
  [anon_sym_Declare] = "Declare",
  [anon_sym_EQ] = "=",
  [anon_sym_Include] = "Include",
  [sym_include_path] = "include_path",
  [sym_string] = "string",
  [sym_env_path] = "env_path",
  [sym_bare_value] = "bare_value",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_leafblock] = "leafblock",
  [sym_leafblock_disabled] = "leafblock_disabled",
  [sym_key_value] = "key_value",
  [sym_key_value_disabled] = "key_value_disabled",
  [sym__value] = "_value",
  [sym_declare] = "declare",
  [sym_include] = "include",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_key_value_repeat1] = "key_value_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_identifier] = sym_identifier,
  [sym_identifier_disabled] = sym_identifier_disabled,
  [sym_comment] = sym_comment,
  [aux_sym_key_value_token1] = aux_sym_key_value_token1,
  [anon_sym_Declare] = anon_sym_Declare,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_Include] = anon_sym_Include,
  [sym_include_path] = sym_include_path,
  [sym_string] = sym_string,
  [sym_env_path] = sym_env_path,
  [sym_bare_value] = sym_bare_value,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_leafblock] = sym_leafblock,
  [sym_leafblock_disabled] = sym_leafblock_disabled,
  [sym_key_value] = sym_key_value,
  [sym_key_value_disabled] = sym_key_value_disabled,
  [sym__value] = sym__value,
  [sym_declare] = sym_declare,
  [sym_include] = sym_include,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_key_value_repeat1] = aux_sym_key_value_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier_disabled] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_key_value_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_Declare] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Include] = {
    .visible = true,
    .named = false,
  },
  [sym_include_path] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_env_path] = {
    .visible = true,
    .named = true,
  },
  [sym_bare_value] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_leafblock] = {
    .visible = true,
    .named = true,
  },
  [sym_leafblock_disabled] = {
    .visible = true,
    .named = true,
  },
  [sym_key_value] = {
    .visible = true,
    .named = true,
  },
  [sym_key_value_disabled] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_declare] = {
    .visible = true,
    .named = true,
  },
  [sym_include] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_key_value_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_key = 1,
  field_name = 2,
  field_path = 3,
  field_value = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_name] = "name",
  [field_path] = "path",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 3},
  [8] = {.index = 12, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0},
  [1] =
    {field_value, 0},
  [2] =
    {field_key, 0},
    {field_value, 1},
  [4] =
    {field_path, 1},
  [5] =
    {field_key, 0},
    {field_value, 1, .inherited = true},
  [7] =
    {field_value, 0, .inherited = true},
    {field_value, 1, .inherited = true},
  [9] =
    {field_key, 0},
    {field_value, 1},
    {field_value, 2, .inherited = true},
  [12] =
    {field_name, 1},
    {field_value, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 9,
  [13] = 11,
  [14] = 10,
  [15] = 15,
  [16] = 15,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 10,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 28,
  [30] = 30,
  [31] = 15,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      ADVANCE_MAP(
        '"', 3,
        '#', 46,
        '$', 57,
        '=', 50,
        'D', 24,
        'I', 34,
        '_', 9,
        '{', 12,
        '}', 14,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(47);
      if (lookahead == '"') ADVANCE(58);
      if (lookahead == '#') ADVANCE(44);
      if (lookahead == '$') ADVANCE(56);
      if (lookahead == '{') ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (lookahead != 0) ADVANCE(60);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(47);
      if (lookahead == '"') ADVANCE(58);
      if (lookahead == '#') ADVANCE(44);
      if (lookahead == '$') ADVANCE(56);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (lookahead != 0) ADVANCE(60);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(54);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(58);
      if (lookahead == '#') ADVANCE(44);
      if (lookahead == '$') ADVANCE(56);
      if (lookahead == 'D') ADVANCE(27);
      if (lookahead == 'I') ADVANCE(35);
      if (lookahead == '_') ADVANCE(59);
      if (lookahead == '}') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      if (lookahead != 0) ADVANCE(60);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(58);
      if (lookahead == '#') ADVANCE(44);
      if (lookahead == '$') ADVANCE(56);
      if (lookahead == '{') ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (lookahead != 0) ADVANCE(60);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(58);
      if (lookahead == '#') ADVANCE(44);
      if (lookahead == '$') ADVANCE(56);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (lookahead != 0) ADVANCE(60);
      END_STATE();
    case 7:
      if (lookahead == '#') ADVANCE(46);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 8:
      if (lookahead == '#') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(53);
      END_STATE();
    case 9:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 10:
      if (eof) ADVANCE(11);
      if (lookahead == '"') ADVANCE(58);
      if (lookahead == '#') ADVANCE(44);
      if (lookahead == '$') ADVANCE(56);
      if (lookahead == 'D') ADVANCE(27);
      if (lookahead == 'I') ADVANCE(35);
      if (lookahead == '_') ADVANCE(59);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      if (lookahead != 0) ADVANCE(60);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(60);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(60);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(36);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(37);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(60);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(30);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(32);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(60);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(31);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(33);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(60);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(26);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(29);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(60);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(18);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(48);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(51);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(19);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(60);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(49);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(60);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(52);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(60);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(16);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(38);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(17);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(60);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(39);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(60);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(20);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(21);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(60);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(25);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(28);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(60);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(22);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(23);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(60);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(60);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier_disabled);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier_disabled);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(60);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ' ||
          lookahead == '"' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(46);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_key_value_token1);
      if (lookahead == '\n') ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_Declare);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_Declare);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(60);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_Include);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_Include);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(60);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_include_path);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_string);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(60);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_env_path);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(60);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_env_path);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_bare_value);
      if (lookahead == '"') ADVANCE(55);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(3);
      if (lookahead != 0) ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_bare_value);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(60);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_bare_value);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(60);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 10},
  [10] = {.lex_state = 10},
  [11] = {.lex_state = 10},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 4},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 10},
  [16] = {.lex_state = 4},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 5},
  [29] = {.lex_state = 5},
  [30] = {.lex_state = 6},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 8},
  [35] = {.lex_state = 7},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_identifier_disabled] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_Declare] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_Include] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_env_path] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(32),
    [sym__statement] = STATE(4),
    [sym_leafblock] = STATE(4),
    [sym_leafblock_disabled] = STATE(4),
    [sym_key_value] = STATE(4),
    [sym_key_value_disabled] = STATE(4),
    [sym_declare] = STATE(4),
    [sym_include] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_identifier_disabled] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
    [anon_sym_Declare] = ACTIONS(11),
    [anon_sym_Include] = ACTIONS(13),
  },
  [STATE(2)] = {
    [sym__statement] = STATE(2),
    [sym_leafblock] = STATE(2),
    [sym_leafblock_disabled] = STATE(2),
    [sym_key_value] = STATE(2),
    [sym_key_value_disabled] = STATE(2),
    [sym_declare] = STATE(2),
    [sym_include] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_identifier_disabled] = ACTIONS(20),
    [sym_comment] = ACTIONS(3),
    [anon_sym_Declare] = ACTIONS(23),
    [anon_sym_Include] = ACTIONS(26),
  },
  [STATE(3)] = {
    [sym__statement] = STATE(3),
    [sym_leafblock] = STATE(3),
    [sym_leafblock_disabled] = STATE(3),
    [sym_key_value] = STATE(3),
    [sym_key_value_disabled] = STATE(3),
    [sym_declare] = STATE(3),
    [sym_include] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [anon_sym_RBRACE] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_identifier_disabled] = ACTIONS(29),
    [sym_comment] = ACTIONS(3),
    [anon_sym_Declare] = ACTIONS(23),
    [anon_sym_Include] = ACTIONS(26),
  },
  [STATE(4)] = {
    [sym__statement] = STATE(2),
    [sym_leafblock] = STATE(2),
    [sym_leafblock_disabled] = STATE(2),
    [sym_key_value] = STATE(2),
    [sym_key_value_disabled] = STATE(2),
    [sym_declare] = STATE(2),
    [sym_include] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(32),
    [sym_identifier] = ACTIONS(7),
    [sym_identifier_disabled] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
    [anon_sym_Declare] = ACTIONS(11),
    [anon_sym_Include] = ACTIONS(13),
  },
  [STATE(5)] = {
    [sym__statement] = STATE(7),
    [sym_leafblock] = STATE(7),
    [sym_leafblock_disabled] = STATE(7),
    [sym_key_value] = STATE(7),
    [sym_key_value_disabled] = STATE(7),
    [sym_declare] = STATE(7),
    [sym_include] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(7),
    [anon_sym_RBRACE] = ACTIONS(34),
    [sym_identifier] = ACTIONS(7),
    [sym_identifier_disabled] = ACTIONS(36),
    [sym_comment] = ACTIONS(3),
    [anon_sym_Declare] = ACTIONS(11),
    [anon_sym_Include] = ACTIONS(13),
  },
  [STATE(6)] = {
    [sym__statement] = STATE(8),
    [sym_leafblock] = STATE(8),
    [sym_leafblock_disabled] = STATE(8),
    [sym_key_value] = STATE(8),
    [sym_key_value_disabled] = STATE(8),
    [sym_declare] = STATE(8),
    [sym_include] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(8),
    [anon_sym_RBRACE] = ACTIONS(38),
    [sym_identifier] = ACTIONS(7),
    [sym_identifier_disabled] = ACTIONS(36),
    [sym_comment] = ACTIONS(3),
    [anon_sym_Declare] = ACTIONS(11),
    [anon_sym_Include] = ACTIONS(13),
  },
  [STATE(7)] = {
    [sym__statement] = STATE(3),
    [sym_leafblock] = STATE(3),
    [sym_leafblock_disabled] = STATE(3),
    [sym_key_value] = STATE(3),
    [sym_key_value_disabled] = STATE(3),
    [sym_declare] = STATE(3),
    [sym_include] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [anon_sym_RBRACE] = ACTIONS(40),
    [sym_identifier] = ACTIONS(7),
    [sym_identifier_disabled] = ACTIONS(36),
    [sym_comment] = ACTIONS(3),
    [anon_sym_Declare] = ACTIONS(11),
    [anon_sym_Include] = ACTIONS(13),
  },
  [STATE(8)] = {
    [sym__statement] = STATE(3),
    [sym_leafblock] = STATE(3),
    [sym_leafblock_disabled] = STATE(3),
    [sym_key_value] = STATE(3),
    [sym_key_value_disabled] = STATE(3),
    [sym_declare] = STATE(3),
    [sym_include] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [anon_sym_RBRACE] = ACTIONS(42),
    [sym_identifier] = ACTIONS(7),
    [sym_identifier_disabled] = ACTIONS(36),
    [sym_comment] = ACTIONS(3),
    [anon_sym_Declare] = ACTIONS(11),
    [anon_sym_Include] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(44), 1,
      ts_builtin_sym_end,
    STATE(11), 1,
      aux_sym_key_value_repeat1,
    STATE(15), 1,
      sym__value,
    ACTIONS(48), 3,
      sym_string,
      sym_env_path,
      sym_bare_value,
    ACTIONS(46), 4,
      sym_identifier,
      sym_identifier_disabled,
      anon_sym_Declare,
      anon_sym_Include,
  [24] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      ts_builtin_sym_end,
    STATE(10), 1,
      aux_sym_key_value_repeat1,
    STATE(15), 1,
      sym__value,
    ACTIONS(54), 3,
      sym_string,
      sym_env_path,
      sym_bare_value,
    ACTIONS(52), 4,
      sym_identifier,
      sym_identifier_disabled,
      anon_sym_Declare,
      anon_sym_Include,
  [48] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
    STATE(10), 1,
      aux_sym_key_value_repeat1,
    STATE(15), 1,
      sym__value,
    ACTIONS(48), 3,
      sym_string,
      sym_env_path,
      sym_bare_value,
    ACTIONS(59), 4,
      sym_identifier,
      sym_identifier_disabled,
      anon_sym_Declare,
      anon_sym_Include,
  [72] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(13), 1,
      aux_sym_key_value_repeat1,
    STATE(16), 1,
      sym__value,
    ACTIONS(61), 3,
      sym_string,
      sym_env_path,
      sym_bare_value,
    ACTIONS(46), 5,
      anon_sym_RBRACE,
      sym_identifier,
      sym_identifier_disabled,
      anon_sym_Declare,
      anon_sym_Include,
  [94] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(14), 1,
      aux_sym_key_value_repeat1,
    STATE(16), 1,
      sym__value,
    ACTIONS(61), 3,
      sym_string,
      sym_env_path,
      sym_bare_value,
    ACTIONS(59), 5,
      anon_sym_RBRACE,
      sym_identifier,
      sym_identifier_disabled,
      anon_sym_Declare,
      anon_sym_Include,
  [116] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(14), 1,
      aux_sym_key_value_repeat1,
    STATE(16), 1,
      sym__value,
    ACTIONS(63), 3,
      sym_string,
      sym_env_path,
      sym_bare_value,
    ACTIONS(52), 5,
      anon_sym_RBRACE,
      sym_identifier,
      sym_identifier_disabled,
      anon_sym_Declare,
      anon_sym_Include,
  [138] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      ts_builtin_sym_end,
    ACTIONS(68), 7,
      sym_identifier,
      sym_identifier_disabled,
      anon_sym_Declare,
      anon_sym_Include,
      sym_string,
      sym_env_path,
      sym_bare_value,
  [154] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 8,
      anon_sym_RBRACE,
      sym_identifier,
      sym_identifier_disabled,
      anon_sym_Declare,
      anon_sym_Include,
      sym_string,
      sym_env_path,
      sym_bare_value,
  [168] = 6,
    ACTIONS(70), 1,
      anon_sym_LBRACE,
    ACTIONS(72), 1,
      sym_comment,
    ACTIONS(74), 1,
      aux_sym_key_value_token1,
    STATE(22), 1,
      aux_sym_key_value_repeat1,
    STATE(31), 1,
      sym__value,
    ACTIONS(76), 3,
      sym_string,
      sym_env_path,
      sym_bare_value,
  [189] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(80), 4,
      sym_identifier,
      sym_identifier_disabled,
      anon_sym_Declare,
      anon_sym_Include,
  [203] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(84), 4,
      sym_identifier,
      sym_identifier_disabled,
      anon_sym_Declare,
      anon_sym_Include,
  [217] = 5,
    ACTIONS(50), 1,
      aux_sym_key_value_token1,
    ACTIONS(72), 1,
      sym_comment,
    STATE(20), 1,
      aux_sym_key_value_repeat1,
    STATE(31), 1,
      sym__value,
    ACTIONS(86), 3,
      sym_string,
      sym_env_path,
      sym_bare_value,
  [235] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(91), 4,
      sym_identifier,
      sym_identifier_disabled,
      anon_sym_Declare,
      anon_sym_Include,
  [249] = 5,
    ACTIONS(72), 1,
      sym_comment,
    ACTIONS(93), 1,
      aux_sym_key_value_token1,
    STATE(20), 1,
      aux_sym_key_value_repeat1,
    STATE(31), 1,
      sym__value,
    ACTIONS(76), 3,
      sym_string,
      sym_env_path,
      sym_bare_value,
  [267] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(97), 4,
      sym_identifier,
      sym_identifier_disabled,
      anon_sym_Declare,
      anon_sym_Include,
  [281] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(101), 4,
      sym_identifier,
      sym_identifier_disabled,
      anon_sym_Declare,
      anon_sym_Include,
  [295] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(105), 4,
      sym_identifier,
      sym_identifier_disabled,
      anon_sym_Declare,
      anon_sym_Include,
  [309] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(109), 4,
      sym_identifier,
      sym_identifier_disabled,
      anon_sym_Declare,
      anon_sym_Include,
  [323] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(113), 4,
      sym_identifier,
      sym_identifier_disabled,
      anon_sym_Declare,
      anon_sym_Include,
  [337] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    STATE(12), 1,
      sym__value,
    ACTIONS(117), 3,
      sym_string,
      sym_env_path,
      sym_bare_value,
  [352] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    STATE(9), 1,
      sym__value,
    ACTIONS(119), 3,
      sym_string,
      sym_env_path,
      sym_bare_value,
  [367] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(25), 1,
      sym__value,
    ACTIONS(121), 3,
      sym_string,
      sym_env_path,
      sym_bare_value,
  [379] = 3,
    ACTIONS(66), 1,
      aux_sym_key_value_token1,
    ACTIONS(72), 1,
      sym_comment,
    ACTIONS(68), 3,
      sym_string,
      sym_env_path,
      sym_bare_value,
  [391] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      ts_builtin_sym_end,
  [398] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_EQ,
  [405] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      sym_include_path,
  [412] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 24,
  [SMALL_STATE(11)] = 48,
  [SMALL_STATE(12)] = 72,
  [SMALL_STATE(13)] = 94,
  [SMALL_STATE(14)] = 116,
  [SMALL_STATE(15)] = 138,
  [SMALL_STATE(16)] = 154,
  [SMALL_STATE(17)] = 168,
  [SMALL_STATE(18)] = 189,
  [SMALL_STATE(19)] = 203,
  [SMALL_STATE(20)] = 217,
  [SMALL_STATE(21)] = 235,
  [SMALL_STATE(22)] = 249,
  [SMALL_STATE(23)] = 267,
  [SMALL_STATE(24)] = 281,
  [SMALL_STATE(25)] = 295,
  [SMALL_STATE(26)] = 309,
  [SMALL_STATE(27)] = 323,
  [SMALL_STATE(28)] = 337,
  [SMALL_STATE(29)] = 352,
  [SMALL_STATE(30)] = 367,
  [SMALL_STATE(31)] = 379,
  [SMALL_STATE(32)] = 391,
  [SMALL_STATE(33)] = 398,
  [SMALL_STATE(34)] = 405,
  [SMALL_STATE(35)] = 412,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [20] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [36] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key_value_disabled, 2, 0, 3),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_key_value_disabled, 2, 0, 3),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_key_value_repeat1, 2, 0, 6),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_key_value_repeat1, 2, 0, 6),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_key_value_repeat1, 2, 0, 6), SHIFT_REPEAT(15),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key_value_disabled, 3, 0, 7),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_key_value_disabled, 3, 0, 7),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_key_value_repeat1, 2, 0, 6), SHIFT_REPEAT(16),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_key_value_repeat1, 1, 0, 2),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_key_value_repeat1, 1, 0, 2),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key_value, 3, 0, 5),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_key_value, 3, 0, 5),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key_value, 2, 0, 1),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_key_value, 2, 0, 1),
  [86] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_key_value_repeat1, 2, 0, 6), SHIFT_REPEAT(31),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leafblock_disabled, 3, 0, 1),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_leafblock_disabled, 3, 0, 1),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leafblock, 4, 0, 1),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_leafblock, 4, 0, 1),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include, 2, 0, 4),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include, 2, 0, 4),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declare, 4, 0, 8),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declare, 4, 0, 8),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leafblock_disabled, 4, 0, 1),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_leafblock_disabled, 4, 0, 1),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leafblock, 3, 0, 1),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_leafblock, 3, 0, 1),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [123] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gum(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "gum",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
