/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 36
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 24
#define ALIAS_COUNT 0
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 8
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACE = 1,
  anon_sym_RBRACE = 2,
  sym_identifier = 3,
  sym_identifier_disabled = 4,
  sym_comment = 5,
  anon_sym_Declare = 6,
  anon_sym_EQ = 7,
  anon_sym_Include = 8,
  sym_include_path = 9,
  sym_string = 10,
  sym_env_path = 11,
  sym_bare_value = 12,
  sym_source_file = 13,
  sym__statement = 14,
  sym_leafblock = 15,
  sym_leafblock_disabled = 16,
  sym_key_value = 17,
  sym_key_value_disabled = 18,
  sym__value = 19,
  sym_declare = 20,
  sym_include = 21,
  aux_sym_source_file_repeat1 = 22,
  aux_sym_key_value_repeat1 = 23,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_identifier] = "identifier",
  [sym_identifier_disabled] = "identifier_disabled",
  [sym_comment] = "comment",
  [anon_sym_Declare] = "Declare",
  [anon_sym_EQ] = "=",
  [anon_sym_Include] = "Include",
  [sym_include_path] = "include_path",
  [sym_string] = "string",
  [sym_env_path] = "env_path",
  [sym_bare_value] = "bare_value",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_leafblock] = "leafblock",
  [sym_leafblock_disabled] = "leafblock_disabled",
  [sym_key_value] = "key_value",
  [sym_key_value_disabled] = "key_value_disabled",
  [sym__value] = "_value",
  [sym_declare] = "declare",
  [sym_include] = "include",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_key_value_repeat1] = "key_value_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_identifier] = sym_identifier,
  [sym_identifier_disabled] = sym_identifier_disabled,
  [sym_comment] = sym_comment,
  [anon_sym_Declare] = anon_sym_Declare,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_Include] = anon_sym_Include,
  [sym_include_path] = sym_include_path,
  [sym_string] = sym_string,
  [sym_env_path] = sym_env_path,
  [sym_bare_value] = sym_bare_value,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_leafblock] = sym_leafblock,
  [sym_leafblock_disabled] = sym_leafblock_disabled,
  [sym_key_value] = sym_key_value,
  [sym_key_value_disabled] = sym_key_value_disabled,
  [sym__value] = sym__value,
  [sym_declare] = sym_declare,
  [sym_include] = sym_include,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_key_value_repeat1] = aux_sym_key_value_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier_disabled] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_Declare] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Include] = {
    .visible = true,
    .named = false,
  },
  [sym_include_path] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_env_path] = {
    .visible = true,
    .named = true,
  },
  [sym_bare_value] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_leafblock] = {
    .visible = true,
    .named = true,
  },
  [sym_leafblock_disabled] = {
    .visible = true,
    .named = true,
  },
  [sym_key_value] = {
    .visible = true,
    .named = true,
  },
  [sym_key_value_disabled] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_declare] = {
    .visible = true,
    .named = true,
  },
  [sym_include] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_key_value_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_key = 1,
  field_name = 2,
  field_path = 3,
  field_value = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_name] = "name",
  [field_path] = "path",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 3},
  [6] = {.index = 8, .length = 2},
  [7] = {.index = 10, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0},
    {field_value, 1},
  [2] =
    {field_path, 1},
  [3] =
    {field_key, 0},
  [4] =
    {field_value, 0},
  [5] =
    {field_key, 0},
    {field_value, 1},
    {field_value, 2, .inherited = true},
  [8] =
    {field_value, 0, .inherited = true},
    {field_value, 1, .inherited = true},
  [10] =
    {field_name, 1},
    {field_value, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 3,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 9,
  [15] = 10,
  [16] = 11,
  [17] = 13,
  [18] = 12,
  [19] = 19,
  [20] = 19,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 28,
  [30] = 27,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      ADVANCE_MAP(
        '"', 1,
        '#', 44,
        '$', 54,
        '=', 47,
        'D', 22,
        'I', 32,
        '_', 7,
        '{', 10,
        '}', 12,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(51);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(55);
      if (lookahead == '#') ADVANCE(42);
      if (lookahead == '$') ADVANCE(53);
      if (lookahead == 'D') ADVANCE(25);
      if (lookahead == 'I') ADVANCE(33);
      if (lookahead == '_') ADVANCE(56);
      if (lookahead == '}') ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (lookahead != 0) ADVANCE(57);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(55);
      if (lookahead == '#') ADVANCE(42);
      if (lookahead == '$') ADVANCE(53);
      if (lookahead == '{') ADVANCE(11);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (lookahead != 0) ADVANCE(57);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(55);
      if (lookahead == '#') ADVANCE(42);
      if (lookahead == '$') ADVANCE(53);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (lookahead != 0) ADVANCE(57);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(44);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 6:
      if (lookahead == '#') ADVANCE(43);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(50);
      END_STATE();
    case 7:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      if (lookahead == '"') ADVANCE(55);
      if (lookahead == '#') ADVANCE(42);
      if (lookahead == '$') ADVANCE(53);
      if (lookahead == 'D') ADVANCE(25);
      if (lookahead == 'I') ADVANCE(33);
      if (lookahead == '_') ADVANCE(56);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (lookahead != 0) ADVANCE(57);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(57);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(57);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(34);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(35);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(57);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(28);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(30);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(57);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(29);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(31);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(57);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(24);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(27);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(57);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(16);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(45);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(48);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(17);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(57);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(46);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(57);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(49);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(57);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(14);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(36);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(15);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(57);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(37);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(57);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(18);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(19);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(57);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(23);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(26);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(57);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(20);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(21);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(57);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(57);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier_disabled);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier_disabled);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(57);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ' ||
          lookahead == '"' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(44);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_Declare);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_Declare);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(57);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_Include);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_Include);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(57);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_include_path);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_string);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(57);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_env_path);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(57);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_env_path);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_bare_value);
      if (lookahead == '"') ADVANCE(52);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(1);
      if (lookahead != 0) ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_bare_value);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(57);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_bare_value);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(57);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 8},
  [10] = {.lex_state = 8},
  [11] = {.lex_state = 8},
  [12] = {.lex_state = 8},
  [13] = {.lex_state = 8},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 8},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 4},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 6},
  [35] = {.lex_state = 5},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_identifier_disabled] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_Declare] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_Include] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_env_path] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(33),
    [sym__statement] = STATE(4),
    [sym_leafblock] = STATE(4),
    [sym_leafblock_disabled] = STATE(4),
    [sym_key_value] = STATE(4),
    [sym_key_value_disabled] = STATE(4),
    [sym_declare] = STATE(4),
    [sym_include] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_identifier_disabled] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
    [anon_sym_Declare] = ACTIONS(11),
    [anon_sym_Include] = ACTIONS(13),
  },
  [STATE(2)] = {
    [sym__statement] = STATE(3),
    [sym_leafblock] = STATE(3),
    [sym_leafblock_disabled] = STATE(3),
    [sym_key_value] = STATE(3),
    [sym_key_value_disabled] = STATE(3),
    [sym_declare] = STATE(3),
    [sym_include] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [anon_sym_RBRACE] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_identifier_disabled] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
    [anon_sym_Declare] = ACTIONS(11),
    [anon_sym_Include] = ACTIONS(13),
  },
  [STATE(3)] = {
    [sym__statement] = STATE(3),
    [sym_leafblock] = STATE(3),
    [sym_leafblock_disabled] = STATE(3),
    [sym_key_value] = STATE(3),
    [sym_key_value_disabled] = STATE(3),
    [sym_declare] = STATE(3),
    [sym_include] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [anon_sym_RBRACE] = ACTIONS(21),
    [sym_identifier] = ACTIONS(23),
    [sym_identifier_disabled] = ACTIONS(26),
    [sym_comment] = ACTIONS(3),
    [anon_sym_Declare] = ACTIONS(29),
    [anon_sym_Include] = ACTIONS(32),
  },
  [STATE(4)] = {
    [sym__statement] = STATE(6),
    [sym_leafblock] = STATE(6),
    [sym_leafblock_disabled] = STATE(6),
    [sym_key_value] = STATE(6),
    [sym_key_value_disabled] = STATE(6),
    [sym_declare] = STATE(6),
    [sym_include] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(35),
    [sym_identifier] = ACTIONS(7),
    [sym_identifier_disabled] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
    [anon_sym_Declare] = ACTIONS(11),
    [anon_sym_Include] = ACTIONS(13),
  },
  [STATE(5)] = {
    [sym__statement] = STATE(2),
    [sym_leafblock] = STATE(2),
    [sym_leafblock_disabled] = STATE(2),
    [sym_key_value] = STATE(2),
    [sym_key_value_disabled] = STATE(2),
    [sym_declare] = STATE(2),
    [sym_include] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_RBRACE] = ACTIONS(37),
    [sym_identifier] = ACTIONS(17),
    [sym_identifier_disabled] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
    [anon_sym_Declare] = ACTIONS(11),
    [anon_sym_Include] = ACTIONS(13),
  },
  [STATE(6)] = {
    [sym__statement] = STATE(6),
    [sym_leafblock] = STATE(6),
    [sym_leafblock_disabled] = STATE(6),
    [sym_key_value] = STATE(6),
    [sym_key_value_disabled] = STATE(6),
    [sym_declare] = STATE(6),
    [sym_include] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(21),
    [sym_identifier] = ACTIONS(39),
    [sym_identifier_disabled] = ACTIONS(42),
    [sym_comment] = ACTIONS(3),
    [anon_sym_Declare] = ACTIONS(29),
    [anon_sym_Include] = ACTIONS(32),
  },
  [STATE(7)] = {
    [sym__statement] = STATE(8),
    [sym_leafblock] = STATE(8),
    [sym_leafblock_disabled] = STATE(8),
    [sym_key_value] = STATE(8),
    [sym_key_value_disabled] = STATE(8),
    [sym_declare] = STATE(8),
    [sym_include] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(8),
    [anon_sym_RBRACE] = ACTIONS(45),
    [sym_identifier] = ACTIONS(17),
    [sym_identifier_disabled] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
    [anon_sym_Declare] = ACTIONS(11),
    [anon_sym_Include] = ACTIONS(13),
  },
  [STATE(8)] = {
    [sym__statement] = STATE(3),
    [sym_leafblock] = STATE(3),
    [sym_leafblock_disabled] = STATE(3),
    [sym_key_value] = STATE(3),
    [sym_key_value_disabled] = STATE(3),
    [sym_declare] = STATE(3),
    [sym_include] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [anon_sym_RBRACE] = ACTIONS(47),
    [sym_identifier] = ACTIONS(17),
    [sym_identifier_disabled] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
    [anon_sym_Declare] = ACTIONS(11),
    [anon_sym_Include] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    STATE(11), 1,
      aux_sym_key_value_repeat1,
    STATE(19), 1,
      sym__value,
    ACTIONS(53), 3,
      sym_string,
      sym_env_path,
      sym_bare_value,
    ACTIONS(51), 4,
      sym_identifier,
      sym_identifier_disabled,
      anon_sym_Declare,
      anon_sym_Include,
  [24] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      ts_builtin_sym_end,
    STATE(12), 1,
      aux_sym_key_value_repeat1,
    STATE(19), 1,
      sym__value,
    ACTIONS(53), 3,
      sym_string,
      sym_env_path,
      sym_bare_value,
    ACTIONS(57), 4,
      sym_identifier,
      sym_identifier_disabled,
      anon_sym_Declare,
      anon_sym_Include,
  [48] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
    STATE(13), 1,
      aux_sym_key_value_repeat1,
    STATE(19), 1,
      sym__value,
    ACTIONS(53), 3,
      sym_string,
      sym_env_path,
      sym_bare_value,
    ACTIONS(61), 4,
      sym_identifier,
      sym_identifier_disabled,
      anon_sym_Declare,
      anon_sym_Include,
  [72] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
    STATE(13), 1,
      aux_sym_key_value_repeat1,
    STATE(19), 1,
      sym__value,
    ACTIONS(53), 3,
      sym_string,
      sym_env_path,
      sym_bare_value,
    ACTIONS(65), 4,
      sym_identifier,
      sym_identifier_disabled,
      anon_sym_Declare,
      anon_sym_Include,
  [96] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      ts_builtin_sym_end,
    STATE(13), 1,
      aux_sym_key_value_repeat1,
    STATE(19), 1,
      sym__value,
    ACTIONS(71), 3,
      sym_string,
      sym_env_path,
      sym_bare_value,
    ACTIONS(69), 4,
      sym_identifier,
      sym_identifier_disabled,
      anon_sym_Declare,
      anon_sym_Include,
  [120] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(16), 1,
      aux_sym_key_value_repeat1,
    STATE(20), 1,
      sym__value,
    ACTIONS(74), 3,
      sym_string,
      sym_env_path,
      sym_bare_value,
    ACTIONS(51), 5,
      anon_sym_RBRACE,
      sym_identifier,
      sym_identifier_disabled,
      anon_sym_Declare,
      anon_sym_Include,
  [142] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(18), 1,
      aux_sym_key_value_repeat1,
    STATE(20), 1,
      sym__value,
    ACTIONS(74), 3,
      sym_string,
      sym_env_path,
      sym_bare_value,
    ACTIONS(57), 5,
      anon_sym_RBRACE,
      sym_identifier,
      sym_identifier_disabled,
      anon_sym_Declare,
      anon_sym_Include,
  [164] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(17), 1,
      aux_sym_key_value_repeat1,
    STATE(20), 1,
      sym__value,
    ACTIONS(74), 3,
      sym_string,
      sym_env_path,
      sym_bare_value,
    ACTIONS(61), 5,
      anon_sym_RBRACE,
      sym_identifier,
      sym_identifier_disabled,
      anon_sym_Declare,
      anon_sym_Include,
  [186] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(17), 1,
      aux_sym_key_value_repeat1,
    STATE(20), 1,
      sym__value,
    ACTIONS(76), 3,
      sym_string,
      sym_env_path,
      sym_bare_value,
    ACTIONS(69), 5,
      anon_sym_RBRACE,
      sym_identifier,
      sym_identifier_disabled,
      anon_sym_Declare,
      anon_sym_Include,
  [208] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(17), 1,
      aux_sym_key_value_repeat1,
    STATE(20), 1,
      sym__value,
    ACTIONS(74), 3,
      sym_string,
      sym_env_path,
      sym_bare_value,
    ACTIONS(65), 5,
      anon_sym_RBRACE,
      sym_identifier,
      sym_identifier_disabled,
      anon_sym_Declare,
      anon_sym_Include,
  [230] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    ACTIONS(81), 7,
      sym_identifier,
      sym_identifier_disabled,
      anon_sym_Declare,
      anon_sym_Include,
      sym_string,
      sym_env_path,
      sym_bare_value,
  [246] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 8,
      anon_sym_RBRACE,
      sym_identifier,
      sym_identifier_disabled,
      anon_sym_Declare,
      anon_sym_Include,
      sym_string,
      sym_env_path,
      sym_bare_value,
  [260] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(85), 4,
      sym_identifier,
      sym_identifier_disabled,
      anon_sym_Declare,
      anon_sym_Include,
  [274] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(89), 4,
      sym_identifier,
      sym_identifier_disabled,
      anon_sym_Declare,
      anon_sym_Include,
  [288] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(93), 4,
      sym_identifier,
      sym_identifier_disabled,
      anon_sym_Declare,
      anon_sym_Include,
  [302] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(97), 4,
      sym_identifier,
      sym_identifier_disabled,
      anon_sym_Declare,
      anon_sym_Include,
  [316] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(101), 4,
      sym_identifier,
      sym_identifier_disabled,
      anon_sym_Declare,
      anon_sym_Include,
  [330] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(105), 4,
      sym_identifier,
      sym_identifier_disabled,
      anon_sym_Declare,
      anon_sym_Include,
  [344] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      anon_sym_LBRACE,
    STATE(9), 1,
      sym__value,
    ACTIONS(109), 3,
      sym_string,
      sym_env_path,
      sym_bare_value,
  [359] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      anon_sym_LBRACE,
    STATE(10), 1,
      sym__value,
    ACTIONS(113), 3,
      sym_string,
      sym_env_path,
      sym_bare_value,
  [374] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      anon_sym_LBRACE,
    STATE(15), 1,
      sym__value,
    ACTIONS(115), 3,
      sym_string,
      sym_env_path,
      sym_bare_value,
  [389] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      anon_sym_LBRACE,
    STATE(14), 1,
      sym__value,
    ACTIONS(117), 3,
      sym_string,
      sym_env_path,
      sym_bare_value,
  [404] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(22), 1,
      sym__value,
    ACTIONS(119), 3,
      sym_string,
      sym_env_path,
      sym_bare_value,
  [416] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      anon_sym_EQ,
  [423] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      ts_builtin_sym_end,
  [430] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      sym_include_path,
  [437] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 24,
  [SMALL_STATE(11)] = 48,
  [SMALL_STATE(12)] = 72,
  [SMALL_STATE(13)] = 96,
  [SMALL_STATE(14)] = 120,
  [SMALL_STATE(15)] = 142,
  [SMALL_STATE(16)] = 164,
  [SMALL_STATE(17)] = 186,
  [SMALL_STATE(18)] = 208,
  [SMALL_STATE(19)] = 230,
  [SMALL_STATE(20)] = 246,
  [SMALL_STATE(21)] = 260,
  [SMALL_STATE(22)] = 274,
  [SMALL_STATE(23)] = 288,
  [SMALL_STATE(24)] = 302,
  [SMALL_STATE(25)] = 316,
  [SMALL_STATE(26)] = 330,
  [SMALL_STATE(27)] = 344,
  [SMALL_STATE(28)] = 359,
  [SMALL_STATE(29)] = 374,
  [SMALL_STATE(30)] = 389,
  [SMALL_STATE(31)] = 404,
  [SMALL_STATE(32)] = 416,
  [SMALL_STATE(33)] = 423,
  [SMALL_STATE(34)] = 430,
  [SMALL_STATE(35)] = 437,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key_value, 2, 0, 1),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_key_value, 2, 0, 1),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key_value_disabled, 2, 0, 1),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_key_value_disabled, 2, 0, 1),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key_value, 3, 0, 5),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_key_value, 3, 0, 5),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key_value_disabled, 3, 0, 5),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_key_value_disabled, 3, 0, 5),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_key_value_repeat1, 2, 0, 6),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_key_value_repeat1, 2, 0, 6),
  [71] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_key_value_repeat1, 2, 0, 6), SHIFT_REPEAT(19),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [76] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_key_value_repeat1, 2, 0, 6), SHIFT_REPEAT(20),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_key_value_repeat1, 1, 0, 4),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_key_value_repeat1, 1, 0, 4),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leafblock_disabled, 3, 0, 3),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_leafblock_disabled, 3, 0, 3),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declare, 4, 0, 7),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declare, 4, 0, 7),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leafblock, 4, 0, 3),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_leafblock, 4, 0, 3),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leafblock, 3, 0, 3),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_leafblock, 3, 0, 3),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leafblock_disabled, 4, 0, 3),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_leafblock_disabled, 4, 0, 3),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include, 2, 0, 2),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include, 2, 0, 2),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [123] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gum(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "gum",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
